# Generated by Django 5.0.4 on 2024-05-16 06:08

import django.db.models.deletion
import master.utils.BOY_UNIQ.unique_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MycategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyproductsModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=master.utils.BOY_UNIQ.unique_filename.genrate_unique_filename)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('mrp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.mycategoriesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
