# Generated by Django 5.0.4 on 2024-05-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MycategoriesModel',
            new_name='categoriesModel',
        ),
        migrations.RenameModel(
            old_name='MyproductsModel',
            new_name='productsModel',
        ),
    ]
