# Generated by Django 5.0.4 on 2024-05-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_mycategoriesmodel_categoriesmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoriesModel',
            new_name='MyCategoriesModel',
        ),
        migrations.RenameModel(
            old_name='productsModel',
            new_name='MyProductsModel',
        ),
    ]
