# Generated by Django 5.0.4 on 2024-05-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_mycustomermodel_is_added_address'),
        ('seller', '0003_rename_categoriesmodel_mycategoriesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.mycustomermodel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.myproductsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
