# Generated by Django 5.0.4 on 2024-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_orderitemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('on_working', 'On Working')], default='unresolved', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
