# Generated by Django 5.1.2 on 2024-10-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=500)),
                ('stoke', models.IntegerField(max_length=100)),
            ],
        ),
    ]
