# Generated by Django 5.0.4 on 2024-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomerModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=255)),
                ('LastName', models.CharField(blank=True, max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Mobile', models.CharField(blank=True, max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('is_activate', models.BooleanField(default=False)),
                ('is_added_address', models.BooleanField(default=False)),
                ('Otp', models.CharField(default='111111', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
