# Generated by Django 5.0.4 on 2024-05-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='customer_id',
            new_name='Customer_id',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='Otp',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='Password',
            new_name='password',
        ),
    ]
