# Generated by Django 5.0.4 on 2024-05-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_mycustomermodel_is_added_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='Customer_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='mycustomermodel',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.CreateModel(
            name='MyAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curent_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.mycustomermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
