# Generated by Django 5.0.4 on 2024-05-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_customer_id_mycustomermodel_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomermodel',
            name='is_added_address',
            field=models.BooleanField(default=False),
        ),
    ]
